# Fields written fresh for the 50-word sample. Everything else in the workbook
# is lifted from the Speak Sarthi seed. Keys: forms, why, trick, usage, own,
# action (before, during, after), cw (confusing word), diff (difference).
A = {
"VRB-001": dict(forms="understand – understood – understood – understanding",
 why="'Understand' is a state verb (a state of mind, not an action), so it normally isn't used in the -ing form.",
 trick="When something finally makes sense, say 'Got it, I understand' out loud — it ties the word to the feeling of clarity.",
 usage="'Sorry, I didn't understand — could you repeat that?' is polite and natural in class or at work.",
 own="Write one sentence about a subject you understand well now but found hard before.",
 action=("hear something confusing","think and ask a question","the idea makes sense: 'Now I understand.'"),
 cw="understand vs know",
 diff="Know = you have the information. Understand = you see how or why it works. You can know a rule without understanding it."),
"VRB-002": dict(forms="forget – forgot – forgotten – forgetting",
 why="After 'forgot to', use the base verb (lock), not the past form (locked).",
 trick="Every night, say one thing you almost forgot today: 'I almost forgot to…'.",
 usage="'Forget to do' = you didn't do it. 'Forget doing' = you did it but have no memory of it.",
 own="Write a sentence about something you once forgot to take to school or work.",
 action=("plan to call a friend","get busy with other work","realise: 'I forgot to call!'"),
 cw="forget vs leave",
 diff="With a place, use leave: 'I left my phone at home.' Forget is for the thing or the action: 'I forgot my phone.'"),
"VRB-003": dict(forms="decide – decided – decided – deciding",
 why="'Decide' is followed by 'to + base verb', not the -ing form.",
 trick="DE-CIDE sounds like 'the side' — you pick one side.",
 usage="'I've decided to…' announces a firm plan. 'I can't decide' is common when choosing.",
 own="Write a sentence about a decision you made this year using 'decided to'.",
 action=("look at two options","compare and think","choose one: 'I decided to take the job.'"),
 cw="decide vs choose",
 diff="Choose = pick from options (choose a shirt). Decide = make up your mind, often about an action (decide to leave)."),
"VRB-004": dict(forms="explain – explained – explained – explaining",
 why="'Explain' does not take the person straight after it. Say: explain something TO someone.",
 trick="EX-PLAIN: make it 'plain' — simple and clear.",
 usage="'Could you explain what this means?' is a polite way to ask for help.",
 own="Write a sentence asking a teacher or senior to explain something to you.",
 action=("someone is confused","break the idea into simple steps","they understand"),
 cw="explain vs tell",
 diff="Tell takes a person directly: 'Tell me the rule.' Explain needs 'to': 'Explain the rule to me.'"),
"VRB-005": dict(forms="arrive – arrived – arrived – arriving",
 why="Use 'arrive at' for a building or small place and 'arrive in' for a city or country — never 'arrive to'.",
 trick="You arrive AT the station and IN the city: small place AT, big place IN.",
 usage="'Arrive home' needs no preposition: 'I arrived home late.'",
 own="Write a sentence about when you arrived at school, college or office today.",
 action=("travel on the bus","reach the stop","walk in: 'I arrived at 9.'"),
 cw="arrive vs reach",
 diff="Reach takes a direct object: 'I reached the office.' Arrive needs at/in: 'I arrived at the office.' Never 'reached to'."),
"VRB-006": dict(forms="choose – chose – chosen – choosing",
 why="'Choose' is irregular: the past is 'chose', not 'choosed'.",
 trick="Double O = two options to look at: chOOse. One O in the past: chOse.",
 usage="'You can choose any one' is common in shops and forms. Also: 'choose between A and B'.",
 own="Write a sentence about something you chose recently (a phone, a course, a dish).",
 action=("see several options","compare them","pick one: 'I chose the blue one.'"),
 cw="choose vs chose",
 diff="Choose (/tʃuːz/, rhymes with 'news') is present. Chose (/tʃəʊz/, rhymes with 'rose') is past."),
"VRB-007": dict(forms="remember – remembered – remembered – remembering",
 why="'Remember + -ing' is for a past memory. 'Remember + to' is for a task you still have to do.",
 trick="RE-MEMBER: bring a 'member' of your past back into your thoughts.",
 usage="'Remember to…' is a friendly reminder: 'Remember to bring your ID.'",
 own="Write one sentence with 'remember + -ing' about a childhood memory.",
 action=("something happens","time passes","it comes back to mind: 'I remember that day.'"),
 cw="remember vs remind",
 diff="You remember something yourself. Someone or something reminds you: 'Remind me to call him.'"),
"VRB-008": dict(forms="teach – taught – taught – teaching",
 why="'Teach' is irregular: the past is 'taught', not 'teached'.",
 trick="TAUGHT rhymes with CAUGHT: what you are taught gets caught in your head.",
 usage="'Can you teach me how to…?' is a natural way to ask someone to show you a skill.",
 own="Write a sentence about a person who taught you something useful.",
 action=("a student can't do something","the teacher shows and explains","the student can do it"),
 cw="teach vs learn",
 diff="The teacher teaches; the student learns. 'He taught me English' / 'I learned English from him.' Never 'He learned me.'"),
"VRB-009": dict(forms="carry – carried – carried – carrying",
 why="A habit uses the simple present, not -ing, and 'always' goes before the main verb.",
 trick="A CART CARRIES things: carry = move something while holding it.",
 usage="Carry often means 'have with you': 'Do you carry cash?'",
 own="Write a sentence about what you always carry in your bag.",
 action=("pick up the bag","walk with it","put it down at home"),
 cw="carry vs bring",
 diff="Carry is about holding something while moving. Bring is about coming towards the speaker with it: 'Bring your notebook tomorrow.'"),
"VRB-010": dict(forms="wait – waited – waited – waiting",
 why="'Wait' needs 'for' before the person or thing: wait FOR someone.",
 trick="Picture a bus-stop sign: 'WAIT FOR BUS HERE' — wait and for always travel together.",
 usage="'Wait a minute' and 'Can you wait for me?' are very common in daily speech.",
 own="Write a sentence about how long you waited for something recently.",
 action=("arrive at the bus stop","stand and watch the road","the bus comes"),
 cw="wait vs expect",
 diff="Wait = spend time until something happens. Expect = think something will happen. 'I'm waiting for the bus; I expect it at 9.'"),
"VRB-011": dict(forms="believe – believed – believed – believing",
 why="'Believe' describes a state of mind, so it doesn't normally take -ing.",
 trick="Never beLIEve a LIE — the word 'lie' is hidden inside.",
 usage="'I believe so' is a polite yes when you are fairly sure.",
 own="Write a sentence about something you believe is important in life.",
 action=("hear a claim","think about it","accept it: 'I believe you.'"),
 cw="believe vs belief",
 diff="Believe is the verb (I believe). Belief is the noun (my belief). Spelling: -ve for the verb, -f for the noun."),
"VRB-012": dict(forms="imagine – imagined – imagined – imagining",
 why="'Imagine' is followed by the -ing form, not 'to + verb'.",
 trick="IMAGinE has an IMAGE inside: you make a picture in your mind.",
 usage="'I can't imagine…' shows surprise or sympathy: 'I can't imagine how hard that was.'",
 own="Write a sentence imagining your life five years from now.",
 action=("close your eyes","picture a place","describe what you saw"),
 cw="imagine vs imagination",
 diff="Imagine is the verb. Imagination is the noun (the ability): 'Use your imagination.'"),
"VRB-013": dict(forms="realize – realized – realized – realizing",
 why="Here 'realize' means becoming aware, a state, so the simple present sounds natural, not -ing.",
 trick="REAL-ize: something suddenly becomes REAL in your mind.",
 usage="'I didn't realize…' is a soft way to apologise: 'Sorry, I didn't realize you were busy.'",
 own="Write a sentence about a time you suddenly realized you had made a mistake.",
 action=("don't notice something","a clue appears","'Oh! Now I realize.'"),
 cw="realize vs recognize",
 diff="Recognize = identify someone or something you know (I recognized her voice). Realize = understand a fact (I realized she was upset). British spelling 'realise' is also correct."),
"VRB-014": dict(forms="suggest – suggested – suggested – suggesting",
 why="'Suggest' can't take object + 'to' verb. Use 'suggest (that) you + base verb' or 'suggest + -ing'.",
 trick="Suggest = Soft advice. Both start with S.",
 usage="'I suggest we…' and 'May I suggest…?' are polite ways to give ideas in meetings.",
 own="Write a sentence suggesting a weekend plan to a friend.",
 action=("a problem comes up","think of an idea","'I suggest we leave early.'"),
 cw="suggest vs advise",
 diff="Advise can take person + to: 'I advise you to rest.' Suggest cannot: 'I suggest (that) you rest.'"),
"VRB-015": dict(forms="describe – described – described – describing",
 why="'Describe' takes a direct object. Don't add 'about', and don't put the person straight after it.",
 trick="DE-SCRIBE: a scribe writes down every detail — describe = give the details.",
 usage="Interviews often start with 'Describe yourself in three words.'",
 own="Write two sentences describing your house or room.",
 action=("look at something","notice colour, size and shape","put it into words"),
 cw="describe vs explain",
 diff="Describe = say what something is like (looks, details). Explain = say why or how it works."),
"VRB-016": dict(forms="mention – mentioned – mentioned – mentioning",
 why="'Mention' already includes the idea of 'about', so it takes a direct object.",
 trick="MENTION = say it for a moMENT only.",
 usage="'Don't mention it' is a polite reply to 'thank you'.",
 own="Write a sentence about something a friend mentioned to you recently.",
 action=("talk about many things","say one thing quickly","move on to the next topic"),
 cw="mention vs discuss",
 diff="Mention = say briefly. Discuss = talk in detail. Neither takes 'about'."),
"VRB-017": dict(forms="admit – admitted – admitted – admitting",
 why="In 'admit to', 'to' is a preposition, so it takes -ing: 'admitted to stealing'. You can also drop 'to': 'admitted stealing'.",
 trick="AD-MIT: you let the truth in, like a hospital admits a patient.",
 usage="'I admit I was wrong' is a strong, honest way to take responsibility.",
 own="Write a sentence admitting a small mistake you made.",
 action=("hide a mistake","feel guilty","say: 'I admit it was me.'"),
 cw="admit vs confess",
 diff="Confess is stronger and often about a crime or sin. Admit is everyday: 'I admit I'm tired.'"),
"VRB-018": dict(forms="argue – argued – argued – arguing",
 why="After a preposition like 'about', use a noun or -ing, not a 'that' clause.",
 trick="ARGUE starts with 'ARG' — the sound of an angry person: 'Arrgh!'",
 usage="Argue WITH someone ABOUT something — both prepositions are needed.",
 own="Write a sentence about something you and a sibling or friend argued about.",
 action=("two people disagree","raise voices and give reasons","stop and calm down"),
 cw="argue vs fight",
 diff="Argue is with words. Fight can be with words or physical. 'They argued' is milder than 'they fought'."),
"VRB-019": dict(forms="agree – agreed – agreed – agreeing",
 why="'Agree' is a full verb, so it doesn't need 'am/is/are' before it.",
 trick="Hindi says 'main sehmat hoon' (I am agreed). In English the verb works alone: 'I agree.'",
 usage="'I agree with you', 'I agree to the terms', 'We agree on the price'.",
 own="Write a sentence about something you agree with your parents about.",
 action=("listen to an opinion","think it's right","nod: 'I agree.'"),
 cw="agree with vs agree to",
 diff="Agree WITH a person or opinion. Agree TO a plan or request. Agree ON a decision a group shares."),
"VRB-020": dict(forms="disagree – disagreed – disagreed – disagreeing",
 why="Use 'disagree with' for a person or opinion. 'Disagree about/on' is for the topic: 'We disagree about politics.'",
 trick="DIS + AGREE = not agree.",
 usage="'I'm afraid I disagree' is a polite way to disagree in meetings.",
 own="Write a polite sentence disagreeing with an idea at work or college.",
 action=("hear an idea","think it's wrong","say: 'I respectfully disagree.'"),
 cw="disagree vs refuse",
 diff="Disagree = have a different opinion. Refuse = say no to doing something."),
"VRB-021": dict(forms="wonder – wondered – wondered – wondering",
 why="'Wonder' holds a question in your mind, so it takes if/whether or a wh-word, not 'that'.",
 trick="WONDER = WHO? WHAT? WHEN? — a mind full of questions.",
 usage="'I was wondering if you could…' is a very polite way to ask a favour.",
 own="Write a polite request starting with 'I was wondering if…'.",
 action=("notice something strange","think 'why?'","ask someone"),
 cw="wonder vs wander",
 diff="Wonder (/ˈwʌndə/, 'wun') = think curiously. Wander (/ˈwɒndə/, 'won') = walk around without a plan."),
"VRB-022": dict(forms="guess – guessed – guessed – guessing",
 why="When 'guess' means 'I think', use the simple present: 'I guess he's at home.'",
 trick="GUESS has a silent U — you just have to guess it's there.",
 usage="'I guess so' = a soft yes. 'Guess what!' introduces news.",
 own="Write a sentence guessing the answer to a question you don't know.",
 action=("face a question","think but don't know for sure","give an answer anyway"),
 cw="guess vs assume",
 diff="A guess admits you might be wrong. Assume means you act as if it's true."),
"VRB-023": dict(forms="doubt – doubted – doubted – doubting",
 why="'Doubt' already carries a negative meaning, so adding 'not' says the opposite of what you mean.",
 trick="DOUBT has a silent B — you doubt it's even there.",
 usage="'No doubt' = certainly. 'I doubt it' = probably not.",
 own="Write a sentence about something you doubt will happen this year.",
 action=("hear a promise","feel unsure","say: 'I doubt it.'"),
 cw="doubt vs suspect",
 diff="'I doubt he's honest' = I think he is NOT honest. 'I suspect he's lying' = I think he IS lying. They point in opposite directions."),
"VRB-024": dict(forms="assume – assumed – assumed – assuming",
 why="'Agree' is a verb, so it takes -s after he/she/it. It never follows 'is'.",
 trick="AS-SUME: act AS if it's SURE, without proof.",
 usage="'I assume you've had lunch?' is a friendly way to check.",
 own="Write a sentence about something you assumed that turned out wrong.",
 action=("see a clue","fill the gap in your mind","act as if it's true"),
 cw="assume vs presume",
 diff="Both mean 'think without proof'. Presume sounds more formal and suggests a stronger reason."),
"VRB-025": dict(forms="conclude – concluded – concluded – concluding",
 why="'Conclude' takes its object directly; no 'to' before it.",
 trick="CON-CLUDE sounds like CLOSE: the end of a speech, book or meeting.",
 usage="'To conclude, …' is a clean way to end a presentation or essay.",
 own="Write the last sentence of a short speech, starting with 'To conclude,'.",
 action=("collect the facts","think them through","reach a decision: 'We concluded that…'"),
 cw="conclude vs include",
 diff="Include = put something inside a group. Conclude = end, or decide after thinking."),
"VRB-026": dict(forms="discuss – discussed – discussed – discussing",
 why="'Discuss' already means 'talk about', so 'discuss about' repeats the idea.",
 trick="Discuss = talk about. The 'about' is already inside the word.",
 usage="'Can we discuss this later?' is a polite way to delay a topic at work.",
 own="Write a sentence about a topic you discussed with your family this week.",
 action=("set a topic","share views and listen","agree on a plan"),
 cw="discuss vs talk about",
 diff="Same meaning, different grammar: discuss the plan / talk about the plan."),
"VRB-027": dict(forms="convince – convinced – convinced – convincing",
 why="The pattern is 'convince someone to do something' or 'convince someone that…', never 'for'.",
 trick="CONVINCE shares a root with 'victory' (Latin vincere, to win): you win their mind.",
 usage="'I'm convinced (that)…' = I'm fully sure.",
 own="Write a sentence about how you convinced someone to try something new.",
 action=("someone is unsure","give reasons and proof","they believe you"),
 cw="convince vs persuade",
 diff="Convince is often about belief (convince him that it's true). Persuade is often about action (persuade him to come). Everyday English uses both for action."),
"VRB-028": dict(forms="persuade – persuaded – persuaded – persuading",
 why="Use 'persuade someone to do something'. The 'that' pattern also needs the person: 'He persuaded me that…'.",
 trick="PERSUADE sounds like 'per sweet': you use sweet, good reasons.",
 usage="Sales and interviews: 'How would you persuade a customer to buy…?'",
 own="Write a sentence about how you persuaded a friend to come with you somewhere.",
 action=("a friend says no","give good reasons","they say yes"),
 cw="persuade vs force",
 diff="Persuade uses reasons, and the other person still chooses. Force leaves no choice."),
"VRB-029": dict(forms="complain – complained – complained – complaining",
 why="The order is: complain TO a person, ABOUT a thing, or THAT + clause. Don't split the clause with 'to the waiter'.",
 trick="COMPLAIN has 'PLAIN' inside: you say plainly that something is wrong.",
 usage="At a shop or hotel, 'I'd like to complain about…' is firm but polite.",
 own="Write a polite sentence complaining about a late delivery.",
 action=("get cold food","call the waiter","tell them the problem"),
 cw="complain vs complaint",
 diff="Complain is the verb. Complaint is the noun. 'I want to complain' / 'I want to make a complaint.'"),
"VRB-030": dict(forms="apologize – apologized – apologized – apologizing",
 why="'Apologize' can't take the person directly. Use 'apologize TO someone FOR something'.",
 trick="Apologize = say sorry: sorry TO you, FOR the mistake — the same prepositions.",
 usage="'I apologize for the delay' is standard in emails and customer service.",
 own="Write an email line apologizing for a late reply.",
 action=("make a mistake","feel sorry","say: 'I apologize for…'"),
 cw="apologize vs apology",
 diff="Apologize is the verb. Apology is the noun: 'I apologize' = 'Please accept my apology.' British spelling: apologise."),
"VRB-031": dict(forms="promise – promised – promised – promising",
 why="After 'will', always use the base verb.",
 trick="Pinky promise: hook your little finger and say 'I promise'.",
 usage="Both work: 'I promise to…' and 'I promise (that) I will…'.",
 own="Write a sentence promising your teacher or boss something for next week.",
 action=("someone needs help","give your word","keep it"),
 cw="promise vs guarantee",
 diff="A promise is personal. A guarantee is formal, often backed in writing or with money: 'a one-year guarantee'."),
"VRB-032": dict(forms="warn – warned – warned – warning",
 why="'Warn' puts the person straight after it: warn someone ABOUT or OF something.",
 trick="WARN sounds like 'war': warn people before danger comes.",
 usage="'I'm warning you' sounds strong. 'Just a warning:' is softer.",
 own="Write a sentence warning a friend about heavy traffic.",
 action=("see danger ahead","tell people quickly","they get ready"),
 cw="warn vs threaten",
 diff="Warn = tell someone about danger to protect them. Threaten = say you will cause harm."),
"VRB-033": dict(forms="advise – advised – advised – advising",
 why="Advise (with S, /z/ sound) is the verb. Advice (with C, /s/ sound) is an uncountable noun, so no 'an'.",
 trick="ICE is a thing, so the noun is advICE.",
 usage="'I'd advise you to…' is polite and professional.",
 own="Write one sentence using both 'advise' and 'advice'.",
 action=("someone has a problem","listen","advise them what to do"),
 cw="advise vs advice",
 diff="Advise (/ədˈvaɪz/) = verb. Advice (/ədˈvaɪs/) = uncountable noun: 'some advice', never 'an advice'."),
"VRB-034": dict(forms="insist – insisted – insisted – insisting",
 why="The pattern is 'insist ON + -ing' or 'insist (that) + clause', not 'insist to'.",
 trick="IN-SIST: you stand firm, IN your position.",
 usage="'I insist!' is common when you offer to pay or help.",
 own="Write a sentence about a time someone insisted on paying for you.",
 action=("someone says no","repeat firmly","they accept"),
 cw="insist vs persist",
 diff="Insist = demand firmly. Persist = keep going for a long time despite problems."),
"VRB-035": dict(forms="claim – claimed – claimed – claiming",
 why="In reported speech about the past, the verb in the that-clause usually moves back a tense.",
 trick="CLAIM rhymes with NAME: you put your name on something as yours or as true.",
 usage="Also used for money or items: 'claim insurance', 'baggage claim'.",
 own="Write a sentence about an advert that claims something you don't believe.",
 action=("have an opinion","say it strongly as fact","others ask for proof"),
 cw="claim vs prove",
 diff="Claim = say something is true. Prove = show evidence that it is true."),
"VRB-036": dict(forms="deny – denied – denied – denying",
 why="'Deny' is followed by -ing or a that-clause, not 'to + verb'.",
 trick="DENY = say 'nay' (no).",
 usage="'He denied the charges' is common in news.",
 own="Write a sentence about someone who denied breaking something.",
 action=("someone accuses you","hear the claim","say: 'No, that's not true.'"),
 cw="deny vs refuse",
 diff="Deny = say something is not true. Refuse = say no to doing something."),
"VRB-037": dict(forms="confirm – confirmed – confirmed – confirming",
 why="'Confirm' takes the thing as its object. The person comes after 'for' or 'to'.",
 trick="CON-FIRM: make it FIRM, with no more doubt.",
 usage="'Could you please confirm the time?' is standard in emails.",
 own="Write an email line confirming a meeting time.",
 action=("a plan is unsure","check the details","'Yes, confirmed for 5 pm.'"),
 cw="confirm vs conform",
 diff="Confirm = make certain. Conform = follow rules or behave like others."),
"VRB-038": dict(forms="predict – predicted – predicted – predicting",
 why="After 'will', always use the base verb, with no -s.",
 trick="PRE-DICT: 'pre' = before, 'dict' = say. Say it before it happens.",
 usage="Weather and sport: 'Experts predict heavy rain this week.'",
 own="Write a sentence predicting the result of a match or exam.",
 action=("study the signs","think about what comes next","say it before it happens"),
 cw="predict vs guess",
 diff="A prediction usually has reasons or data behind it. A guess may have none."),
"VRB-039": dict(forms="recall – recalled – recalled – recalling",
 why="'Recall' is followed by -ing for a past memory, like 'remember + -ing'.",
 trick="RE-CALL: call a memory back again.",
 usage="'Do you recall…?' sounds formal. In daily talk, 'Do you remember…?' is more common.",
 own="Write a sentence starting 'I clearly recall…'.",
 action=("an event happens","years pass","bring it back to mind"),
 cw="recall vs remind",
 diff="You recall something yourself. Something reminds you. Companies also 'recall' faulty products (call them back)."),
"VRB-040": dict(forms="recognize – recognized – recognized – recognizing",
 why="'Yesterday' fixes the action in the past, so the verb must be past tense.",
 trick="RE-COGNIZE: 're' = again, 'cognize' = know. Know again.",
 usage="'I didn't recognize you!' is a friendly greeting when someone has changed.",
 own="Write a sentence about someone you didn't recognize at first.",
 action=("see a face","search your memory","'Oh, it's Rahul!'"),
 cw="recognize vs realize",
 diff="Recognize = identify someone or something known. Realize = understand a fact. British spelling: recognise."),
"VRB-041": dict(forms="reflect – reflected – reflected – reflecting",
 why="When it means 'think deeply', use 'reflect on' (or 'upon'), not 'about'.",
 trick="A mirror reflects your face; when you reflect, your mind looks back at itself.",
 usage="'Take some time to reflect' is common in teaching and coaching.",
 own="Write a sentence reflecting on what you learned this month.",
 action=("finish a task","think back over what went well or badly","plan to do better"),
 cw="reflect vs reflex",
 diff="Reflect = think deeply, or bounce back light. Reflex = an automatic body reaction."),
"VRB-042": dict(forms="consider – considered – considered – considering",
 why="'Consider' is always followed by -ing, not 'to + verb'.",
 trick="CON-SIDER: look at all SIDEs before you decide.",
 usage="'Please consider…' is a polite request in formal letters.",
 own="Write a sentence about a change you are considering making.",
 action=("get an offer","weigh pros and cons","decide"),
 cw="consider vs decide",
 diff="Consider = think about options. Decide = make the final choice. Considering comes first."),
"VRB-043": dict(forms="define – defined – defined – defining",
 why="'Define' takes a direct object; don't add 'about'.",
 trick="DE-FINE comes from Latin finis, 'boundary': draw a boundary around a meaning.",
 usage="Exam questions often say 'Define the term…'.",
 own="Write a sentence defining the word 'friend' in your own way.",
 action=("see an unclear word","find its exact meaning","state it clearly"),
 cw="define vs describe",
 diff="Define = give the exact meaning. Describe = give details of what something is like."),
"VRB-044": dict(forms="clarify – clarified – clarified – clarifying",
 why="'Clarify' takes a direct object; don't add 'about'.",
 trick="CLAR-ify: make it CLEAR (same root).",
 usage="'Just to clarify, …' is a polite way to check facts in a meeting.",
 own="Write a sentence starting 'Just to clarify,'.",
 action=("people are confused","explain more simply","it becomes clear"),
 cw="clarify vs explain",
 diff="Explain = make something understood. Clarify = make something that was confusing clearer, often after a first explanation."),
"VRB-045": dict(forms="interpret – interpreted – interpreted – interpreting",
 why="The pattern is 'interpret something AS something', not 'interpret that'.",
 trick="INTER-PRET: go between ('inter') two people and give the meaning.",
 usage="An interpreter translates speech live; a translator works with written text.",
 own="Write a sentence about how you interpreted a friend's silence.",
 action=("see a sign or hear words","think what they mean","decide the meaning"),
 cw="interpret vs translate",
 diff="Translate = change words into another language. Interpret = explain the meaning (also used for live spoken translation)."),
"VRB-046": dict(forms="wake – woke – woken – waking",
 why="'Wake' is irregular: the past is 'woke', not 'waked'.",
 trick="WAKE → WOKE → WOKEN, like BREAK → BROKE → BROKEN.",
 usage="'Wake up' is more common than 'wake' alone: 'Wake me up at 6.'",
 own="Write a sentence about what time you woke up today.",
 action=("sleep","the alarm rings","open your eyes: 'I woke up at 6.'"),
 cw="wake vs awake",
 diff="Wake (up) is the action. Awake is the state: 'I woke up at 6 and I'm still awake.'"),
"VRB-047": dict(forms="sleep – slept – slept – sleeping",
 why="'Sleep' is irregular: the past is 'slept', not 'sleeped'.",
 trick="SLEEP → SLEPT, like KEEP → KEPT and SWEEP → SWEPT.",
 usage="'Sleep well!' and 'Did you sleep well?' are everyday greetings.",
 own="Write a sentence about how many hours you slept last night.",
 action=("lie down","close your eyes and rest","wake up fresh"),
 cw="sleep vs asleep",
 diff="Sleep is the verb. Asleep is the state: 'The baby is asleep.' Fall asleep = start sleeping."),
"VRB-048": dict(forms="wash – washed – washed – washing",
 why="The present continuous needs am/is/are + -ing.",
 trick="WASH = Water And Soap Help.",
 usage="'Wash up' means wash the dishes in British English, wash hands and face in American English.",
 own="Write a sentence about when you wash your clothes.",
 action=("hands are dirty","use soap and water","they are clean"),
 cw="wash vs wipe",
 diff="Wash = clean with water. Wipe = clean by rubbing, often with a cloth."),
"VRB-049": dict(forms="brush – brushed – brushed – brushing",
 why="'Yesterday' needs the past tense 'brushed'.",
 trick="BRUSH sounds like the 'brrsh' of a toothbrush.",
 usage="'Brush your teeth', 'brush your hair' — no 'the' before teeth or hair.",
 own="Write a sentence about how many times a day you brush your teeth.",
 action=("put toothpaste on the brush","brush for two minutes","rinse your mouth"),
 cw="brush vs comb",
 diff="A comb has one row of teeth; a brush has many bristles. You can brush or comb your hair, but only brush your teeth."),
"VRB-050": dict(forms="dress – dressed – dressed – dressing",
 why="'Dress' is the main verb here, so the simple present needs no 'am'.",
 trick="Dress as a verb = put on your dress (clothes).",
 usage="'Get dressed' is more common than 'dress': 'Get dressed, we're late!'",
 own="Write a sentence about how long it takes you to get dressed in the morning.",
 action=("take clothes out","put them on","ready: 'I'm dressed.'"),
 cw="dress vs wear",
 diff="Dress / get dressed = the action of putting clothes on. Wear = have clothes on: 'I'm wearing a blue shirt.'"),
}
