# Words from the 910-word workbook (54 columns) that get the two new columns.
# id: (spelling tip, action sequence or None for non-verbs)
X = {
"VRB-251": ("Double P, and 'ci' in the middle: ap-PRE-ci-ate.", ("someone helps you","notice the value of their help","say 'I really appreciate it'")),
"VRB-252": ("One S between two vowels: he-SI-tate, not 'hessitate'.", ("want to say something","pause, unsure","finally speak — or stay quiet")),
"VRB-253": ("POST + PONE: 'post' (after) + 'pone' (put). Silent-looking T is spoken: pohst-POHN.", ("a meeting is fixed for Monday","something comes up","the meeting moves to Friday")),
"ADJ-252": ("CON-VEN-I-ENT: the -IENT ending, like 'patient'.", None),
"ADV-092": ("GENUINE + LY: keep the E — genuinELY.", None),
"VRB-255": ("Double F: a-FF-ord.", ("check your wallet","compare the price with your money","buy it, or decide you can't afford it")),
"VRB-260": ("One C, double M: re-C-o-MM-end.", ("try a good restaurant","tell a friend it's good","the friend goes there")),
"VRB-261": ("STRUG-GLE: double G, like two hands gripping hard.", ("face a hard task","try again and again","slowly manage it")),
"PHR-154": ("Two words: END UP. No hyphen as a verb.", ("start with one plan","things change on the way","finally land somewhere unexpected")),
"ADJ-256": ("IM-PRESS-ED: double S, then -ed.", None),
"ADV-093": ("APPARENT + LY: double P, one R, -ENT not -ANT.", None),
"ADV-094": ("BASIC + ALLY: basic-ALLY, not 'basicly'.", None),
"ADV-095": ("DEFINITE + LY: keep the E; it's -ITE, not -ATE ('definately' is wrong).", None),
"VRB-264": ("DE-SERVE: the S sounds like Z.", ("work hard for months","your effort is noticed","you receive the reward you earned")),
"VRB-265": ("DIS-TURB: -URB like 'curb'.", ("someone is studying","you make noise","they lose focus")),
"VRB-266": ("RE-MIND: put something back in someone's MIND.", ("a friend may forget","send them a message","they remember the task")),
"VRB-267": ("RE-SPOND → RESPONSE: the D becomes SE in the noun.", ("receive a message","think of a reply","send your answer")),
"VRB-268": ("Double T: a-TT-end. The noun is 'attendance' (-ANCE).", ("get an invitation","go to the event","take part and leave")),
"VRB-269": ("Double R: a-RR-ange.", ("have a plan","book tickets and set a time","everything is ready")),
"VRB-270": ("COM-PARE: -ARE like 'care'. The noun is 'comparison' (-ISON).", ("see two phones","check price and features side by side","decide which is better")),
"VRB-271": ("ES-TI-MATE: 'mate' at the end.", ("look at the job","guess the cost roughly","give a number")),
"VRB-272": ("RE-QUIRE: -QUIRE like 'choir' sound. The noun is 'requirement'.", ("read the rules","see what is needed","prepare it")),
"PHR-159": ("Two words: CARRY ON. Past: carried on (Y becomes I).", ("start a task","get interrupted","keep going")),
"PHR-160": ("Two words: BACK OUT. 'Backout' as one word is rare.", ("agree to join","feel unsure","say you won't do it after all")),
"ADJ-262": ("STRICT: one syllable, two Ts — S-T-R-I-C-T.", None),
"ADJ-263": ("OB-VI-OUS: -IOUS ending, like 'previous'.", None),
"ADJ-264": ("TEM-PO-RA-RY: four syllables — don't drop the -RA- ('tempory' is wrong).", None),
"ADV-097": ("UN + FORTUNATE + LY: keep the E — unfortunatELY.", None),
"PRP-071": ("REGARD + ING: 'regarding', one word.", None),
"VRB-275": ("AD-MIRE → ADMIRATION: the E drops in the noun.", ("see someone's good work","feel respect","want to be like them")),
"VRB-282": ("IG-NORE: -NORE like 'more'.", ("someone calls your name","you hear but don't answer","they feel ignored")),
"VRB-284": ("Double R: inte-RR-upt.", ("someone is speaking","you start talking","they stop mid-sentence")),
"VRB-285": ("PRE-TEND: -TEND like 'attend'. The noun is 'pretence' (UK).", ("know the truth","act as if it's different","others may believe you")),
"VRB-286": ("PROVE → PROOF: the verb has V, the noun has F.", ("make a claim","show facts and evidence","others accept it's true")),
"VRB-287": ("RE-FUSE: stress on FUSE (verb). REF-use (noun) = rubbish.", ("receive a request","think it over","say no")),
"VRB-288": ("Double C and double E: su-CC-EE-d.", ("set a goal","work hard","reach it")),
"VRB-289": ("SUS-PECT: -PECT like 'expect'.", ("notice something odd","think someone may be guilty","watch them carefully")),
"PHR-164": ("Two words as a verb: SHOW OFF. The noun is 'show-off' (with a hyphen).", ("get a new phone","show it to everyone again and again","people feel annoyed")),
"PHR-166": ("Two words: TAKE AFTER. Past: took after.", ("a child grows up","looks and acts like a parent","people say 'she takes after her mother'")),
"ADJ-270": ("FA-MIL-IAR: -IAR ending, like 'peculiar'.", None),
"ADJ-272": ("SUIT + ABLE: the E-less 'suit' + able.", None),
"ADJ-273": ("FLU-ENT: -ENT not -ANT. The noun is 'fluency'.", None),
"ADJ-274": ("CROWD + ED: the -ed is a full syllable — KROW-did.", None),
"ADJ-276": ("SIM-I-LAR: -AR ending, not -ER ('similer' is wrong).", None),
"ADV-099": ("FRANK + LY.", None),
"ADV-100": ("GRADUAL + LY: double L — graduaLLy.", None),
"ADV-101": ("PROPER + LY.", None),
"ADV-102": ("ESPECIAL + LY: double L — especiaLLy. Starts with E, not 'specially'.", None),
"ADV-104": ("SERIOUS + LY.", None),
"VRB-294": ("LEND → LENT: the past ends in T.", ("a friend needs money","give it for a short time","they pay it back later")),
"VRB-295": ("OWE: silent W, rhymes with 'go'. The phrase is 'owing to' (= because of).", ("borrow money","you still have to pay it back","you owe it until you pay")),
}
